### ISSUE TITLE
erreur 501 à l'archivage d'un projet

### ISSUE THREAD

**Issue by tonthon** [CroissanceCommune/autonomie#502]
Traceback (most recent call last):
  File "/var/www/autonomie/lib/python2.7/site-packages/pyramid_exclog-1.0-py2.7.egg/pyramid_exclog/__init__.py", line 134, in exclog_tween
    response = handler(request)
  File "/var/www/autonomie/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/var/www/autonomie/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/var/www/autonomie/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 100, in tm_tween
    response = handler(request)
  File "/var/www/autonomie/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/var/www/autonomie/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/var/www/autonomie/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/var/www/autonomie/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/var/www/autonomie/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/var/www/autonomie/lib/python2.7/site-packages/pyramid/viewderivers.py", line 300, in secured_view
    return view(context, request)
  File "/var/www/autonomie/lib/python2.7/site-packages/pyramid/viewderivers.py", line 409, in viewresult_to_response
    result = view(context, request)
  File "/var/www/autonomie/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/var/www/autonomie/lib/python2.7/site-packages/autonomie-4.0.13-py2.7.egg/autonomie/views/project.py", line 303, in project_archive
    request.route_path("company_projects", id=context.company_id)
NameError: global name 'context' is not defined

**Comment by tonthon** [comment]
Je ne reproduis pas ce problème, il a dû être corrigé par les différents refactoring
