### ISSUE TITLE
Migrations cassées ?

### ISSUE THREAD

**Issue by JocelynDelalande** [CroissanceCommune/autonomie#647]
Quand j'essaye de migrer sur la branche courante de dév (4.2.0a), j'ai 1 migration qui échoue (les autres passent).

Contexte, je pars du dump anonymisé fourni par @tonthon qui est à la migration 44f964dc36a2 au départ.

## 2a66d798c55d 4.2.0a : Migrate parcours data (cc @paul-kilya )

```
± am upgrade --rev 2a66d798c55d
2018-07-11 17:00:13,859 INFO  Upgrading autonomie:alembic: ([alembic.autonomie.upgrade:137])
2018-07-11 17:00:13,860 DEBUG new transaction ([txn.139706775746304.__init__:110])
2018-07-11 17:00:13,873 INFO  Context impl MySQLImpl. ([alembic.runtime.migration.__init__:109])
2018-07-11 17:00:13,874 INFO  Will assume non-transactional DDL. ([alembic.runtime.migration.__init__:114])
2018-07-11 17:00:13,878 INFO  Upgrading from 2e4c3172fc54 to 2a66d798c55d... ([alembic.autonomie.upgrade_func:149])
2018-07-11 17:00:13,894 INFO  Running upgrade 44f964dc36a2 -> 2a66d798c55d, 4.2.0a : Migrate parcours data ([alembic.runtime.migration.run_migrations:309])
Traceback (most recent call last):
  File "/home/jocelyn/dev/autonomie/autonomie/alembic/env.py", line 50, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/jocelyn/.virtualenvs/autonomie/local/lib/python2.7/site-packages/alembic-0.8.2-py2.7.egg/alembic/runtime/environment.py", line 797, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/jocelyn/.virtualenvs/autonomie/local/lib/python2.7/site-packages/alembic-0.8.2-py2.7.egg/alembic/runtime/migration.py", line 312, in run_migrations
    step.migration_fn(**kw)
  File "/home/jocelyn/dev/autonomie/autonomie/alembic/versions/4_2_0a_migrate_parcours_data_2a66d798c55d.py", line 239, in upgrade
    situations_id, stages_id = populate_default_datas()
  File "/home/jocelyn/dev/autonomie/autonomie/alembic/versions/4_2_0a_migrate_parcours_data_2a66d798c55d.py", line 58, in populate_default_datas
    if CareerStage.query().count() == 0:
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 3029, in count
    return self.from_self(col).scalar()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2783, in scalar
    ret = self.one()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2754, in one
    ret = self.one_or_none()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2724, in one_or_none
    ret = list(self)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2795, in __iter__
    return self._execute_and_instances(context)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2818, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
  File "build/bdist.linux-x86_64/egg/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "build/bdist.linux-x86_64/egg/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
OperationalError: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'career_stage.stage_type' in 'field list'") [SQL: u'SELECT count(*) AS count_1 \nFROM (SELECT career_stage.id AS career_stage_id, career_stage.active AS career_stage_active, career_stage.name AS career_stage_name, career_stage.cae_situation_id AS career_stage_cae_situation_id, career_stage.stage_type AS career_stage_stage_type \nFROM career_stage \nWHERE career_stage.active = true ORDER BY career_stage.name) AS anon_1']
```

**Comment by tonthon** [comment]
N'est plus d'actualité
