### ISSUE TITLE
Erreur à la migration depuis la version 4.1

### ISSUE THREAD

**Issue by tonthon** [CroissanceCommune/autonomie#670]
Depuis une base de production, je tombe sur l'erreur suivante 
```
None - 2018-09-03 12:25:30,569 INFO  Running upgrade 44f964dc36a2 -> 2a66d798c55d, 4.2.0a : Migrate parcours data ([alembic.runtime.migration.run_migrations:309])
Traceback (most recent call last):
  File "/home/gas/autonomie/autonomie/autonomie/alembic/env.py", line 50, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/alembic/runtime/environment.py", line 797, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/alembic/runtime/migration.py", line 312, in run_migrations
    step.migration_fn(**kw)
  File "/home/gas/autonomie/autonomie/autonomie/alembic/versions/4_2_0a_migrate_parcours_data_2a66d798c55d.py", line 241, in upgrade
    clean_database()
  File "/home/gas/autonomie/autonomie/autonomie/alembic/versions/4_2_0a_migrate_parcours_data_2a66d798c55d.py", line 220, in clean_database
    op.drop_constraint('fk_user_datas_sortie_motif_id', 'user_datas', type_='foreignkey')
  File "<string>", line 8, in drop_constraint
  File "<string>", line 3, in drop_constraint
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/alembic/operations/ops.py", line 145, in drop_constraint
    return operations.invoke(op)
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/alembic/operations/base.py", line 318, in invoke
    return fn(self, operation)
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/alembic/operations/toimpl.py", line 146, in drop_constraint
    schema=operation.schema,
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/alembic/ddl/impl.py", line 183, in drop_constraint
    self._exec(schema.DropConstraint(const))
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/alembic/ddl/impl.py", line 118, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1002, in _execute_ddl
    compiled
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
OperationalError: (_mysql_exceptions.OperationalError) (1091, "Can't DROP FOREIGN KEY `fk_user_datas_sortie_motif_id`; check that it exists") [SQL: u'ALTER TABLE user_datas DROP FOREIGN KEY fk_user_datas_sortie_motif_id']
```

On cherche à dropper une contraintes qui n'a pas encore été ajoutée si on effectue la migration d'un coup.

Solutions possibles : 
Solution 1- Ajouter la table depuis le script de migration précédent
Solution 2- Supprimer ces appels et partir du principe qu'on part toujours d'une base en version 4.1

J'opterai plutôt pour la solution 2

**Comment by tonthon** [comment]
Corrigé ici : 
https://github.com/CroissanceCommune/autonomie/commit/774470cb81f6445a4dc8e77582d3a66d649abca9
