### ISSUE TITLE
Parcours : erreur à l'affichage du parcours pour des comptes qui existaient avant migration

### ISSUE THREAD

**Issue by tonthon** [CroissanceCommune/autonomie#678]
## Contexte
Quelles actions a-t-on effectuées ou doit-on effectuer pour que le bogue se manifeste ?
Depuis un compte existant (qui existait déjà avant migration), aller dans /users/<identifiant du compte>/userdatas/career_path/

## Ce qui devrait se passer
Quel est le comportement attendu ? (éventuellement : "aucun", ou bien "message «OK»")
La page devrait afficher le partcours

## Ce qui se passe
Comment le bogue se manifeste-t-il ?
Une erreur 500 est soulevée 

```
Traceback (most recent call last):
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/pyramid_mako-1.0.2-py2.7.egg/pyramid_mako/__init__.py", line 148, in __call__
    result = template.render_unicode(**system)
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/mako/template.py", line 454, in render_unicode
    as_unicode=True)
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/mako/runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/mako/runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/mako/runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "/home/gas/autonomie/autonomie/autonomie/templates/layouts/default.mako", line 102, in render_body
    <%block name='beforecontent' />
  File "/home/gas/autonomie/autonomie/autonomie/templates/layouts/user.mako", line 73, in render_content
    </%block>
  File "/home/gas/autonomie/autonomie/autonomie/templates/userdatas/career_path.mako", line 48, in render_mainblock
    <td>${stage.career_stage.name}</td>
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by tonthon** [comment]
![configuration_parcours](https://user-images.githubusercontent.com/592723/45082864-98ff9780-b0fa-11e8-8b1b-6403377db80f.png)
