### ISSUE TITLE
Modèles de document : Erreur 500 au chargement du modèle

### ISSUE THREAD

**Issue by paul-kilya** [CroissanceCommune/autonomie#719]
Erreur 500 lorsqu'on enregistre un nouveau modèle de document (Configuration, Gestion Sociale).

Constaté sur différents serveurs.

```
mod_wsgi (pid=2977): Exception occurred processing WSGI script '/var/www/html/autonomie/pyramid.wsgi'.
Traceback (most recent call last):
  File "fanstatic-1.0a5-py2.7.egg/fanstatic/publisher.py", line 219, in __call__
    return self.app(environ, start_response)
  File "fanstatic-1.0a5-py2.7.egg/fanstatic/injector.py", line 64, in __call__
    response = request.get_response(self.app)
  File "build/bdist.linux-x86_64/egg/webob/request.py", line 1316, in send
    application, catch_exc_info=False)
  File "build/bdist.linux-x86_64/egg/webob/request.py", line 1280, in call_application
    app_iter = application(self.environ, start_response)
  File "pyramid-1.8.3-py2.7.egg/pyramid/router.py", line 233, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "pyramid-1.8.3-py2.7.egg/pyramid/router.py", line 208, in invoke_subrequest
    response = handle_request(request)
  File "pyramid_tm-2.2-py2.7.egg/pyramid_tm/__init__.py", line 171, in tm_tween
    reraise(*exc_info)
  File "pyramid_tm-2.2-py2.7.egg/pyramid_tm/__init__.py", line 136, in tm_tween
    response = handler(request)
  File "pyramid-1.8.3-py2.7.egg/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "pyramid-1.8.3-py2.7.egg/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "pyramid-1.8.3-py2.7.egg/pyramid/router.py", line 155, in handle_request
    view_name
  File "pyramid-1.8.3-py2.7.egg/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "pyramid-1.8.3-py2.7.egg/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "pyramid-1.8.3-py2.7.egg/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "pyramid-1.8.3-py2.7.egg/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "pyramid-1.8.3-py2.7.egg/pyramid/viewderivers.py", line 300, in secured_view
    return view(context, request)
  File "pyramid-1.8.3-py2.7.egg/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "pyramid-1.8.3-py2.7.egg/pyramid/viewderivers.py", line 135, in _class_view
    response = inst()
  File "autonomie-4.2.0a0-py2.7.egg/autonomie/views/__init__.py", line 653, in __call__
    result = FormView.__call__(self)
  File "pyramid_deform-0.2-py2.7.egg/pyramid_deform/__init__.py", line 109, in __call__
    result = success_method(validated)
  File "autonomie-4.2.0a0-py2.7.egg/autonomie/views/files.py", line 246, in submit_success
    self.persist_to_database(appstruct)
  File "autonomie-4.2.0a0-py2.7.egg/autonomie/views/files.py", line 220, in persist_to_database
    file_object.parent_id = self._parent().id
AttributeError: 'RootFactory' object has no attribute 'id'
```

**Comment by tonthon** [comment]
C'est un problème de contexte, le self._parent() qui renvoie le contexte courant renvoie la RootFactory (le contexte par défaut), il doit manquer un traverse= dans la configuration de la vue qui est appelée.
