### ISSUE TITLE
Conflit dans les numéros de factures

### ISSUE THREAD

**Issue by tonthon** [CroissanceCommune/autonomie#961]
Version 4.2.0 
Le nouveau système de numérotation des factures ne permet pas de valider des factures dans une CAE existante 
```
Traceback (most recent call last):
  File "/var/www/autonomie/local/lib/python2.7/site-packages/pyramid_exclog/__init__.py", line 134, in exclog_tween
    response = handler(request)
  File "/var/www/autonomie/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 171, in tm_tween
    reraise(*exc_info)
  File "/var/www/autonomie/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 136, in tm_tween
    response = handler(request)
  File "/var/www/autonomie/local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/var/www/autonomie/local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/var/www/autonomie/local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/var/www/autonomie/local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/var/www/autonomie/local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/var/www/autonomie/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/var/www/autonomie/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/var/www/autonomie/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 300, in secured_view
    return view(context, request)
  File "/var/www/autonomie/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/var/www/autonomie/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 135, in _class_view
    response = inst()
  File "/var/www/autonomie/local/lib/python2.7/site-packages/autonomie-4.2.0-py2.7.egg/autonomie/views/status.py", line 144, in __call__
    self.set_status(status, params)
  File "/var/www/autonomie/local/lib/python2.7/site-packages/autonomie-4.2.0-py2.7.egg/autonomie/views/status.py", line 112, in set_status
    post_params = self.status_process(status, params)
  File "/var/www/autonomie/local/lib/python2.7/site-packages/autonomie-4.2.0-py2.7.egg/autonomie/views/status.py", line 87, in status_process
    **params
  File "/var/www/autonomie/local/lib/python2.7/site-packages/autonomie-4.2.0-py2.7.egg/autonomie/models/task/task.py", line 720, in set_status
    **kw
  File "/var/www/autonomie/local/lib/python2.7/site-packages/autonomie-4.2.0-py2.7.egg/autonomie/models/action_manager.py", line 170, in process
    return action.process(context, request, request.user.id, **params)
  File "/var/www/autonomie/local/lib/python2.7/site-packages/autonomie-4.2.0-py2.7.egg/autonomie/models/action_manager.py", line 83, in process
    return self.callback(request, model, user_id=user_id, **kw)
  File "/var/www/autonomie/local/lib/python2.7/site-packages/autonomie-4.2.0-py2.7.egg/autonomie/models/task/actions.py", line 67, in invoice_valid_callback
    _set_invoice_number(request, task, **kw)
  File "/var/www/autonomie/local/lib/python2.7/site-packages/autonomie-4.2.0-py2.7.egg/autonomie/models/task/actions.py", line 33, in _set_invoice_number
    template,
  File "/var/www/autonomie/local/lib/python2.7/site-packages/autonomie-4.2.0-py2.7.egg/autonomie/models/services/invoice_sequence_number.py", line 139, in assign_number
    'Invoice number collision, rolling back to avoid it'
ValueError: Invoice number collision, rolling back to avoid it
```

**Comment by JocelynDelalande** [comment]
OK, je pense que j'ai compris le problème.

Le code fait bien son job de détecter les doublons, il n'y a pas (je crois) de bug dans la logique du code, mais plutôt un bug dans les données existantes

Ce que je propose 

- ajouter un champ booléen `task.legacy_number`
- définir ce champ à `TRUE` pour les anciennes factures
- définir ce champ à `FALSE` puor les nouvelles factures
- ignorer les `legacy_number == true` lors de la détection de doublons

Pour les structures ayant utilisé autonomie < 4.2 :

- inciter les structures à passer, pour l'exercice 2019, ou bien à un n° unique (`SEQGLOBAL`), ou bien à préfixer leurs n° de facture avec l'année. (ex: « 2019-000001 »)

Il vaudrait mieux, je pense, que l'on revert #962 et #966 avant de déployer de nouvelles instances, ça risquerait d'impacter négativement les coops qui se mettent à utiliser autonomie directement en 4.2.

Si cette solution vous convient, je peux faire ça demain.

**Comment by JocelynDelalande** [comment]
> En complément de la proposition, il faut s'assurer que le format de numéro de facture configuré permette une unicité des numéros de facture.

Pas simple.

**Comment by JocelynDelalande** [comment]
Mais pas impossible :-)
